### ISSUE TITLE
I can point out some lines that you repeated yourself at index.css

### ISSUE THREAD

**Issue by juan-galdino** [saubhagyaashish/interactive-rating-component-main#1]
Some properties in css sometimes achieves the same result, but there's no need to maintain the 2 properties that makes the same in your code. So you could erase some lines that will not affect your design and your code will still works, and also, will make more sense to read and maintain. There are a few things that I found for you that will help you write better css. 
Hope you find this helpful...

There's no need to the presence of the property _'font-family: Overpass'_ in almost all your classes...
Honestly, you can pass this property to your **'container'** class  (the big fatther) and all the "**childs**" of container class will inherit the font family, eliminating some lines of your code. 
Bonus: some classes also don't need a _'font-weight'_ property. Like `<h1>` tag font weight will always be 700 by default. Same with `<p>` tag, it's font weight is always be 400 by default, erase that too...
 
The same happens with the display: flex property, but this problem can be a little difficult to specify here, i'd recommend to see some tutorials of Flexbox on youtube to better comprehension. So I did a little refactor that still works on your code, I commented every line that is overwritten by others properties, you should test this and see if it still working.

```css

* {
  margin: 0;
  padding: 0;
}

/*I ruled the font-family here once*/
.container {
  font-family: Overpass;
  display: flex;
  align-items: center;
  justify-content: center;
  flex-direction: column;
  height: 100vh;
  background-color: hsl(216, 12%, 8%);
}

/* the card don't need to flex here */
.feedback-card {
  background-color: #1a212b;
  height: 26rem;
  width: 26rem;
  padding: 34px;
  border-radius: 2rem;
  /* display: flex;
  flex-direction: column; */
}
.feedback-card-star {
  height: 58px;
  width: 58px;
  border-radius: 50%;
  background-color: #262f38;
  display: flex;
  align-items: center;
  justify-content: center;
}
h1 {
  /* font-family: Overpass; */
  /* font-weight: 700; */
  font-size: 2rem;
  margin-top: 37px;
  margin-bottom: 25px;
  color: hsl(0, 0%, 100%);
}
p {
  /* font-family: Overpass; */
  /* font-weight: 400; */
  font-size: 1.2rem;
  color: hsl(217, 12%, 63%);
}
.feedback-card-ratings {
  display: flex;
  align-items: center;
  justify-content: space-around;
  text-align: center;
  margin-top: 33px;
}
input[type="radio"][name="votingNumbers"] {
  display: none;
}

/* here the display property was changed 2 times, so, display:flex will be ruled here as the cascade flows. */
label {
  /* display: inline-block; */
  /* font-family: Overpass; */
  /* font-weight: 400; */
  font-size: 1.2rem;
  color: hsl(217, 12%, 63%);
  background-color: #262f38;
  height: 48px;
  width: 48px;
  /* text-align: center; */
  display: flex;
  align-items: center;
  justify-content: space-around;
  border-radius: 50%;
}
label:hover {
  background-color: hsl(25, 97%, 53%);
  color: hsl(0, 0%, 100%);
  cursor: pointer;
  transition: 0.3s;
}
input[type="radio"][name="votingNumbers"]:checked + label {
  background-color:  hsl(217, 12%, 63%);
  color: hsl(0, 0%, 100%);
}
.submitbutton {
  width: 380px;
  height: 49px;
  background-color: hsl(25, 97%, 53%);
  color: hsl(0, 0%, 100%);
  margin-top: 33px;
  border-radius: 50rem;
  font-size: larger;
  /* font-family: Overpass; */
  border: 0px;
}
.submitbutton:hover {
  background-color: hsl(0, 0%, 100%);
  color: hsl(25, 97%, 53%);
  cursor: pointer;
  transition: 0.3s;
}

.thankyouCard{
  background-color: #1a212b;
  height: 26rem;
  width: 26rem;
  padding: 34px;
  border-radius: 2rem;
  display: none;
  align-items: center;
  flex-direction: column;
}
.thankyouCard-thanks{
  text-align: center;
}
.votingReview{
  display: flex;
  align-items: center;
  justify-content: center;
  /* font-family: Overpass; */
  /* font-weight: 400; */
  background-color:  hsl(213, 19%, 18%);
  color: hsl(25, 97%, 53%);
  margin-top: 3rem;
  height: 1.5rem;
  width: 16rem;
  border-radius: 2.5rem;
}

```

Happy studying!
